import type { Metadata } from "next";

import Header from "@/components/Header/Header";
import Search from "@/components/Search/Search";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Mini Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Search />
        {children}
      </body>
    </html>
  );
}
